;; File names and extensions share one icon/color definition so the mappings
;; cannot drift apart. Names and extensions are matched case-insensitively.

(provide file-icon file-color file-icon-style?)

(define DEFAULT-FILE-STYLE (list "󰈔" "#6d8086"))

(define (fm-file-style icon color) (list icon color))

(define *fm-name-styles*
  (hash
    "makefile"          (fm-file-style "" "#6d8086")
    "gnumakefile"       (fm-file-style "" "#6d8086")
    "cmakelists.txt"    (fm-file-style "" "#6d8086")
    "readme"            (fm-file-style "" "#dddddd")
    "readme.md"         (fm-file-style "" "#dddddd")
    "license"           (fm-file-style "" "#d0bf41")
    "license.md"        (fm-file-style "" "#d0bf41")
    "copying"           (fm-file-style "" "#d0bf41")
    "changelog"         (fm-file-style "" "#dddddd")
    "changelog.md"      (fm-file-style "" "#dddddd")
    "dockerfile"        (fm-file-style "" "#458ee6")
    "compose.yml"       (fm-file-style "" "#458ee6")
    "compose.yaml"      (fm-file-style "" "#458ee6")
    "docker-compose.yml"  (fm-file-style "" "#458ee6")
    "docker-compose.yaml" (fm-file-style "" "#458ee6")
    ".dockerignore"     (fm-file-style "" "#458ee6")
    ".gitignore"        (fm-file-style "" "#f69a1b")
    ".gitattributes"    (fm-file-style "" "#f69a1b")
    ".gitmodules"       (fm-file-style "" "#f69a1b")
    ".gitlab-ci.yml"    (fm-file-style "" "#e24329")
    ".editorconfig"     (fm-file-style "" "#6d8086")
    ".env"              (fm-file-style "󰒓" "#89e051")
    ".bashrc"           (fm-file-style "" "#89e051")
    ".bash_profile"     (fm-file-style "" "#89e051")
    ".zshrc"            (fm-file-style "" "#89e051")
    ".zprofile"         (fm-file-style "" "#89e051")
    "cargo.toml"        (fm-file-style "" "#dea584")
    "cargo.lock"        (fm-file-style "󰾢" "#e5c07b")
    "package.json"      (fm-file-style "" "#f1e05a")
    "package-lock.json" (fm-file-style "" "#f1e05a")
    "yarn.lock"         (fm-file-style "" "#2c8ebb")
    "pnpm-lock.yaml"    (fm-file-style "" "#f9ad00")
    "deno.json"         (fm-file-style "" "#dddddd")
    "deno.jsonc"        (fm-file-style "" "#dddddd")
    "go.mod"            (fm-file-style "" "#519aba")
    "go.sum"            (fm-file-style "" "#519aba")
    "requirements.txt"  (fm-file-style "" "#ffbc03")
    "pyproject.toml"    (fm-file-style "" "#ffbc03")
    "gemfile"           (fm-file-style "" "#701516")
    "rakefile"          (fm-file-style "" "#701516")))

(define *fm-extension-styles*
  (hash
    ;; Programming languages and templates
    "asm"    (fm-file-style "" "#6d8086")
    "astro"  (fm-file-style "" "#e23f67")
    "awk"    (fm-file-style "" "#4d5a5e")
    "c"      (fm-file-style "" "#599eff")
    "cc"     (fm-file-style "" "#519aba")
    "cpp"    (fm-file-style "" "#519aba")
    "cxx"    (fm-file-style "" "#519aba")
    "h"      (fm-file-style "" "#a074c4")
    "hh"     (fm-file-style "" "#a074c4")
    "hpp"    (fm-file-style "" "#a074c4")
    "cs"     (fm-file-style "" "#596706")
    "clj"    (fm-file-style "" "#8dc149")
    "cljs"   (fm-file-style "" "#519aba")
    "cljc"   (fm-file-style "" "#8dc149")
    "cr"     (fm-file-style "" "#c8c8c8")
    "dart"   (fm-file-style "" "#03589c")
    "el"     (fm-file-style "" "#8172be")
    "elm"    (fm-file-style "" "#519aba")
    "erl"    (fm-file-style "" "#b83998")
    "hrl"    (fm-file-style "" "#b83998")
    "ex"     (fm-file-style "" "#a074c4")
    "exs"    (fm-file-style "" "#a074c4")
    "fnl"    (fm-file-style "" "#fff3d7")
    "fs"     (fm-file-style "" "#519aba")
    "fsx"    (fm-file-style "" "#519aba")
    "go"     (fm-file-style "" "#519aba")
    "groovy" (fm-file-style "" "#4a687c")
    "hs"     (fm-file-style "" "#a074c4")
    "java"   (fm-file-style "" "#cc3e44")
    "jl"     (fm-file-style "" "#a270ba")
    "js"     (fm-file-style "" "#cbcb41")
    "mjs"    (fm-file-style "" "#cbcb41")
    "cjs"    (fm-file-style "" "#cbcb41")
    "jsx"    (fm-file-style "" "#20c2e3")
    "kt"     (fm-file-style "" "#7f52ff")
    "kts"    (fm-file-style "" "#7f52ff")
    "lua"    (fm-file-style "" "#51a0cf")
    "nim"    (fm-file-style "" "#f3d400")
    "nix"    (fm-file-style "" "#7ebae4")
    "nu"     (fm-file-style "" "#3aa675")
    "php"    (fm-file-style "" "#a074c4")
    "pl"     (fm-file-style "" "#519aba")
    "pm"     (fm-file-style "" "#519aba")
    "proto"  (fm-file-style "" "#6d8086")
    "ps1"    (fm-file-style "" "#4273ca")
    "py"     (fm-file-style "" "#ffbc03")
    "pyi"    (fm-file-style "" "#ffbc03")
    "r"      (fm-file-style "" "#519aba")
    "rb"     (fm-file-style "" "#701516")
    "rs"     (fm-file-style "" "#dea584")
    "scala"  (fm-file-style "" "#cc3e44")
    "scm"    (fm-file-style "󰘧" "#eeeeee")
    "sol"    (fm-file-style "" "#519aba")
    "svelte" (fm-file-style "" "#ff3e00")
    "swift"  (fm-file-style "" "#e37933")
    "tcl"    (fm-file-style "󰛓" "#1e5cb3")
    "ts"     (fm-file-style "" "#519aba")
    "mts"    (fm-file-style "" "#519aba")
    "cts"    (fm-file-style "" "#519aba")
    "tsx"    (fm-file-style "" "#1354bf")
    "vim"    (fm-file-style "" "#019833")
    "vue"    (fm-file-style "" "#8dc149")
    "zig"    (fm-file-style "" "#f69a1b")

    ;; Web, data, configuration and build files
    "css"     (fm-file-style "" "#42a5f5")
    "scss"    (fm-file-style "" "#f55385")
    "sass"    (fm-file-style "" "#f55385")
    "less"    (fm-file-style "" "#563d7c")
    "html"    (fm-file-style "" "#e44d26")
    "htm"     (fm-file-style "" "#e44d26")
    "haml"    (fm-file-style "󰅴" "#eaeae1")
    "hbs"     (fm-file-style "󰌞" "#f0772b")
    "graphql" (fm-file-style "" "#e535ab")
    "gql"     (fm-file-style "" "#e535ab")
    "json"    (fm-file-style "" "#cbcb41")
    "jsonc"   (fm-file-style "" "#cbcb41")
    "json5"   (fm-file-style "" "#cbcb41")
    "yaml"    (fm-file-style "" "#6d8086")
    "yml"     (fm-file-style "" "#6d8086")
    "toml"    (fm-file-style "" "#9c4221")
    "xml"     (fm-file-style "󰗀" "#e37933")
    "csv"     (fm-file-style "" "#89e051")
    "tsv"     (fm-file-style "" "#89e051")
    "ini"     (fm-file-style "󰯂" "#6d8086")
    "conf"    (fm-file-style "󰯂" "#6d8086")
    "cfg"     (fm-file-style "󰯂" "#6d8086")
    "properties" (fm-file-style "󰯂" "#6d8086")
    "env"     (fm-file-style "󰒓" "#89e051")
    "lock"    (fm-file-style "󰾢" "#e5c07b")
    "diff"    (fm-file-style "󰦓" "#41535b")
    "patch"   (fm-file-style "󰦓" "#41535b")
    "cmake"   (fm-file-style "" "#6d8086")
    "gradle"  (fm-file-style "" "#02303a")
    "sln"     (fm-file-style "󰘐" "#854cc7")
    "tf"      (fm-file-style "" "#5f43e9")
    "tfvars"  (fm-file-style "" "#5f43e9")
    "hcl"     (fm-file-style "" "#5f43e9")

    ;; Shells and command files
    "sh"    (fm-file-style "" "#4d5a5e")
    "bash"  (fm-file-style "" "#4d5a5e")
    "zsh"   (fm-file-style "" "#89e051")
    "fish"  (fm-file-style "" "#4d5a5e")
    "bat"   (fm-file-style "" "#519aba")
    "cmd"   (fm-file-style "" "#519aba")

    ;; Documents and text
    "md"       (fm-file-style "" "#dddddd")
    "markdown" (fm-file-style "" "#dddddd")
    "mdx"      (fm-file-style "" "#dddddd")
    "txt"      (fm-file-style "󰈙" "#89e051")
    "rtf"      (fm-file-style "󰈙" "#89e051")
    "org"      (fm-file-style "" "#77aa99")
    "tex"      (fm-file-style "" "#3d6117")
    "bib"      (fm-file-style "󱉟" "#cbcb41")
    "pdf"      (fm-file-style "󰈦" "#b30b00")
    "doc"      (fm-file-style "󰈬" "#185abd")
    "docx"     (fm-file-style "󰈬" "#185abd")
    "xls"      (fm-file-style "󰈛" "#217346")
    "xlsx"     (fm-file-style "󰈛" "#217346")
    "ppt"      (fm-file-style "󰈧" "#d24726")
    "pptx"     (fm-file-style "󰈧" "#d24726")
    "epub"     (fm-file-style "" "#e37933")
    "ipynb"    (fm-file-style "" "#51a0cf")

    ;; Images, audio and video
    "png"  (fm-file-style "󰸭" "#a074c4")
    "jpg"  (fm-file-style "󰈥" "#a074c4")
    "jpeg" (fm-file-style "󰈥" "#a074c4")
    "gif"  (fm-file-style "󰵸" "#a074c4")
    "webp" (fm-file-style "󰈥" "#a074c4")
    "avif" (fm-file-style "󰈥" "#a074c4")
    "bmp"  (fm-file-style "󰈥" "#a074c4")
    "ico"  (fm-file-style "󰈥" "#cbcb41")
    "svg"  (fm-file-style "󰜡" "#ffb13b")
    "mp3"  (fm-file-style "󰈣" "#00afff")
    "aac"  (fm-file-style "󰈣" "#00afff")
    "flac" (fm-file-style "󰈣" "#00afff")
    "wav"  (fm-file-style "󰈣" "#00afff")
    "ogg"  (fm-file-style "󰈣" "#00afff")
    "m4a"  (fm-file-style "󰈣" "#00afff")
    "mp4"  (fm-file-style "󰈫" "#fd971f")
    "mkv"  (fm-file-style "󰈫" "#fd971f")
    "mov"  (fm-file-style "󰈫" "#fd971f")
    "avi"  (fm-file-style "󰈫" "#fd971f")
    "webm" (fm-file-style "󰈫" "#fd971f")

    ;; Archives, packages, fonts, databases and binaries
    "zip"    (fm-file-style "󰗄" "#eca517")
    "7z"     (fm-file-style "󰗄" "#eca517")
    "rar"    (fm-file-style "󰗄" "#eca517")
    "tar"    (fm-file-style "󰗄" "#eca517")
    "gz"     (fm-file-style "󰗄" "#eca517")
    "bz2"    (fm-file-style "󰗄" "#eca517")
    "xz"     (fm-file-style "󰗄" "#eca517")
    "zst"    (fm-file-style "󰗄" "#eca517")
    "deb"    (fm-file-style "" "#a80030")
    "rpm"    (fm-file-style "" "#ee0000")
    "dmg"    (fm-file-style "󰿔" "#6d8086")
    "iso"    (fm-file-style "" "#d0bf41")
    "ttf"    (fm-file-style "" "#dddddd")
    "otf"    (fm-file-style "" "#dddddd")
    "woff"   (fm-file-style "" "#dddddd")
    "woff2"  (fm-file-style "" "#dddddd")
    "db"     (fm-file-style "󰆼" "#dad8d8")
    "sqlite" (fm-file-style "󰆼" "#dad8d8")
    "sqlite3" (fm-file-style "󰆼" "#dad8d8")
    "sql"    (fm-file-style "󰆎" "#e38c00")
    "log"    (fm-file-style "󰌱" "#6d8086")
    "wasm"   (fm-file-style "" "#654ff0")
    "exe"    (fm-file-style "" "#6d8086")
    "dll"    (fm-file-style "" "#6d8086")
    "so"     (fm-file-style "" "#6d8086")))

(define (fm-file-extension name)
  (define parts (split-many name "."))
  (if (> (length parts) 1)
      (string-downcase (list-ref parts (- (length parts) 1)))
      ""))

(define (file-icon-style? value)
  (or (equal? value 'simple)
      (equal? value 'icons)
      (equal? value 'full)))

(define (fm-file-style-for name)
  (or (hash-try-get *fm-name-styles* (string-downcase name))
      (hash-try-get *fm-extension-styles* (fm-file-extension name))
      DEFAULT-FILE-STYLE))

(define (file-icon name #:icon-style [icon-style 'full])
  (unless (file-icon-style? icon-style)
    (error! "file-icon: icon-style must be 'simple, 'icons, or 'full"))
  (car (if (equal? icon-style 'simple)
           DEFAULT-FILE-STYLE
           (fm-file-style-for name))))

(define (file-color name)
  (list-ref (fm-file-style-for name) 1))
